name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with the default branch of your repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (required by the `actions/deploy-pages` action)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Create the directory structure for deployment
      - name: Prepare static site for deployment
        run: |
          mkdir -p public
          cp -r slideshow/index.html public/
          cp -r slideshow/images public/

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
